"""
F11 -- how the four reference-model defects were found.

The paper claims that a detailed reference model can be misconfigured in ways
that produce plausible annual totals while raising no warning. That claim is
carried by prose; this figure carries the evidence. Each defect has a visible
signature in an hourly series, and none of the four appears in an annual total.

The hourly series come from ``results/paper/validation_corrected/hourly/``,
regenerated by ``tools/diagnostics/ep_hourly_defect_signatures.py`` from the
COMMITTED IDFs with output variables added and nothing else changed. Each run is
asserted against the annual totals already committed in
``validation_corrected.csv`` before its series are written, so the re-run is the
same measurement rather than a second one.

WHICH STATE EACH PANEL IS IN
----------------------------
Only defect 4 has its defective state committed -- the pre-height-fix IDF is
retained under ``results/paper_pre_wind_profile/``. Panel 4 is therefore
instrumented in the DEFECTIVE state. Defects 1-3 were repaired in the shared IDF
builder and no defective input survives, so panels 1-3 instrument the REPAIRED
state and mark what the defective state read as an explicit, labelled gap. No
defective model is re-created in order to draw it, and no series is
reconstructed from an annual total.
"""

from __future__ import annotations

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import ListedColormap
from matplotlib.patches import Patch

import figstyle as F

ISO_COLOR = "#0072B2"       # the ISO 52016-1 side, as in F1 and F12
EP_COLOR = "#E69F00"        # the EnergyPlus reference, as in F1 and F12
DEFECT_COLOR = "#D55E00"    # Okabe-Ito vermillion: the implementation-defect hue
OFF_COLOR = "#EDEDED"

CP_AIR = 1006.0             # J/(kg K), for reading H_ve back off a mass flow
H_VE_ISO = 48.4             # W/K, the designed ventilation conductance on the ISO side

# Committed, and quoted rather than measured here.
HOURS_AS_PUBLISHED = 686    # alignment.md: ideal-loads run hours in the defective case
HUMIDIFICATION_KWH = 300.0  # alignment.md / examples/baseline_vs_energyplus.py: "~300 kWh/yr"


def _panel_1(ax, hourly) -> dict:
    """Defect 1 -- no designed ventilation was ever delivered."""
    oa = hourly["ideal_loads_outdoor_air_mass_flow_kg_s"]
    vent = hourly["zone_ventilation_mass_flow_kg_s"]
    if oa.max() != 0.0:
        raise F.MissingQuantity(
            "the ideal-loads outdoor-air stream is not identically zero in the "
            "repaired case; panel 1's premise no longer holds"
        )
    hours = np.arange(1, 8761)

    ax.plot(hours, vent, lw=0.35, color=EP_COLOR, alpha=0.9,
            label="Repaired: zone air exchange, delivered every hour")
    ax.axhline(0.0, color=DEFECT_COLOR, lw=2.0,
               label="As published: outdoor-air flow = 0 in all 8,760 h")
    # The ISO reference line is H_ve / c_p, not the measured mean: it is what the
    # ISO side required, and the measured mean is what the repair delivers.
    ax.axhline(H_VE_ISO / CP_AIR, color=ISO_COLOR, lw=1.3, ls=(0, (5, 3)),
               label=f"ISO 52016-1 requirement: $H_{{ve}}$ = {H_VE_ISO} W/K "
                     f"({H_VE_ISO / CP_AIR:.4f} kg/s)")

    ax.set_xlim(0, 8760)
    ax.set_ylim(-0.006, vent.max() * 1.34)
    ax.set_xlabel("Hour of the year")
    ax.set_ylabel("Ventilation air mass flow (kg/s)")
    ax.set_xticks([0, 2190, 4380, 6570, 8760])
    ax.legend(loc="upper left", fontsize=7.0, ncol=1)

    ax.annotate(
        f"Mean {vent.mean():.4f} kg/s → $H_{{ve}}$ = {vent.mean() * CP_AIR:.1f} W/K,\n"
        f"non-zero in {int((vent > 0).sum()):,} of 8,760 h",
        xy=(0.985, 0.36), xycoords="axes fraction", ha="right", va="top",
        fontsize=7.4, color=F.INK, linespacing=1.4,
        bbox=dict(boxstyle="round,pad=0.35", facecolor="white",
                  edgecolor=F.MUTED, linewidth=0.7),
    )
    return {
        "vent_mean": float(vent.mean()),
        "H_ve_measured": float(vent.mean() * CP_AIR),
        "oa_nonzero_hours": int((oa > 0).sum()),
    }


def _panel_2(ax, hourly) -> dict:
    """Defect 2 -- outdoor air on the ideal-loads system is delivered intermittently."""
    on = hourly["ideal_loads_supply_air_mass_flow_kg_s"] > 0.0
    grid = on.reshape(365, 24).T.astype(float)      # hour-of-day x day-of-year

    ax.imshow(grid, aspect="auto", origin="lower", interpolation="nearest",
              cmap=ListedColormap([OFF_COLOR, DEFECT_COLOR]), vmin=0, vmax=1,
              extent=(0.5, 365.5, -0.5, 23.5))
    ax.set_xlabel("Day of the year")
    ax.set_ylabel("Hour of the day")
    ax.set_yticks([0, 6, 12, 18, 23])
    ax.set_xticks([1, 91, 182, 274, 365])
    ax.grid(False)

    n_on = int(on.sum())
    ax.legend(
        handles=[
            Patch(facecolor=DEFECT_COLOR, edgecolor="none",
                  label=f"Ideal-loads system running — {n_on:,} h "
                        f"({100 * n_on / 8760:.1f} %)"),
            Patch(facecolor=OFF_COLOR, edgecolor=F.MUTED, linewidth=0.5,
                  label="Free-floating in the deadband — no outdoor air"),
        ],
        loc="lower left", fontsize=6.8, ncol=1, framealpha=0.96,
    )
    # The midday band carries almost no plant operation, so the note sits there
    # rather than below the axes.
    ax.text(
        0.5, 0.60,
        f"ISO 52016-1 applies $H_{{ve}}$ in $\\bf{{all\\ 8,760\\ h}}$.\n"
        f"As published, the defective configuration ran {HOURS_AS_PUBLISHED} h "
        f"({100 * HOURS_AS_PUBLISHED / 8760:.1f} %); the repaired case\n"
        f"shown here runs {n_on:,} h, because delivering the air every hour "
        f"raises\nthe load the plant has to meet.",
        transform=ax.transAxes, ha="center", va="center",
        fontsize=6.9, color=F.INK, linespacing=1.45,
        bbox=dict(boxstyle="round,pad=0.35", facecolor="white",
                  edgecolor=F.MUTED, linewidth=0.7),
    )
    return {"on_hours": n_on, "on_pct": 100.0 * n_on / 8760}


def _panel_3(ax, hourly) -> dict:
    """Defect 3 -- humidification of the ventilation air booked as heating."""
    sens = np.cumsum(hourly["heating_sensible_J"]) / F.J_PER_KWH
    total = np.cumsum(hourly["heating_total_J"]) / F.J_PER_KWH
    gap = float(total[-1] - sens[-1])
    if abs(gap) > 1e-6:
        raise F.MissingQuantity(
            f"the repaired reference books {gap:.6f} kWh of non-sensible heating; "
            "panel 3's premise is that both humidity controls are None"
        )
    hours = np.arange(1, 8761)

    ax.plot(hours, total, lw=3.4, color=EP_COLOR, alpha=0.85,
            label="Reference, as instrumented: TOTAL heating")
    ax.plot(hours, sens, lw=1.2, color=ISO_COLOR, ls=(0, (4, 2.5)),
            label="Reference, as instrumented: SENSIBLE heating")

    end = float(sens[-1])
    top = end + HUMIDIFICATION_KWH
    # The defective endpoint is committed; its path through the year is not, and
    # is drawn as an explicit gap rather than interpolated.
    ax.add_patch(plt.Rectangle((8760 * 0.70, end), 8760 * 0.30, HUMIDIFICATION_KWH,
                               facecolor="none", edgecolor=DEFECT_COLOR,
                               hatch="////", linewidth=1.1, zorder=3))
    ax.annotate(
        f"≈{HUMIDIFICATION_KWH:.0f} kWh/yr booked as heating by\n"
        "$\\tt{ConstantSupplyHumidityRatio}$ — endpoint only;\n"
        "the shape through the year was not retained",
        xy=(8760 * 0.70, top), xytext=(0, 7), textcoords="offset points",
        ha="center", va="bottom",
        fontsize=6.9, color=DEFECT_COLOR, linespacing=1.4, fontweight="bold",
    )

    ax.set_xlim(0, 8760)
    ax.set_ylim(0, top * 1.22)
    ax.set_xlabel("Hour of the year")
    ax.set_ylabel("Cumulative heating on the reference (kWh)")
    ax.set_xticks([0, 2190, 4380, 6570, 8760])
    ax.yaxis.set_major_formatter(lambda v, _: f"{v:,.0f}")
    ax.legend(loc="lower right", fontsize=7.0)
    ax.annotate(
        f"Total − sensible = {gap:.3f} kWh, in every one of 8,760 hours.\n"
        "That subtraction is the audit the defect would have failed.",
        xy=(0.03, 0.755), xycoords="axes fraction", ha="left", va="top",
        fontsize=7.2, color=F.INK, linespacing=1.4,
        bbox=dict(boxstyle="round,pad=0.35", facecolor="white",
                  edgecolor=F.MUTED, linewidth=0.7),
    )
    return {"end_kWh": end, "gap_kWh": gap}


def _panel_4(ax, hourly) -> dict:
    """Defect 4 -- the west wall's external film driven by wind at the wrong height."""
    wall = hourly["westwall_surface_wind_m_s"]
    site = hourly["site_wind_m_s"]
    bins = np.arange(0.0, 18.5, 0.5)

    counts_site, _, _ = ax.hist(
        site, bins=bins, color=ISO_COLOR, alpha=0.62,
        label=f"ISO 52016-1 drove $h_{{ce}}$ with {site.mean():.2f} m/s "
              f"(station column, 10 m)")
    counts_wall, _, _ = ax.hist(
        wall, bins=bins, color=DEFECT_COLOR, alpha=0.62,
        label=f"EnergyPlus drove the west wall with {wall.mean():.2f} m/s "
              f"(evaluated at z = 1.35 m)")

    for value, colour in ((site.mean(), ISO_COLOR), (wall.mean(), DEFECT_COLOR)):
        ax.axvline(value, color=colour, lw=1.6, ls=(0, (4, 2)))
    ax.axvline(4.0, color=F.INK, lw=1.1, ls=(0, (1.5, 1.5)))
    # Headroom above the tallest bar, so the legend and the pivot note have
    # somewhere to sit that is not on top of the distribution.
    ax.set_ylim(0, max(counts_site.max(), counts_wall.max()) * 1.46)
    ax.annotate("4 m/s", xy=(4.0, 0.995), xycoords=("data", "axes fraction"),
                xytext=(0, -3), textcoords="offset points",
                ha="center", va="top", fontsize=7.0, color=F.INK,
                bbox=dict(boxstyle="round,pad=0.25", facecolor="white",
                          edgecolor="none"))

    ax.set_xlim(0, 14)
    ax.set_xlabel("Wind speed driving the external film (m/s)")
    ax.set_ylabel("Hours of the year")
    ax.legend(loc="upper right", fontsize=7.0)
    ax.annotate(
        "The pivot: $h_{ce} = 4u + 4$ equals the ISO constant\n"
        "of 20 W/(m²·K) at u = 4 m/s.\n"
        f"Factor {site.mean() / wall.mean():.2f} between the two distributions.\n"
        f"Above the pivot: {100 * (site > 4).mean():.1f} % of hours on the ISO side\n"
        f"against {100 * (wall > 4).mean():.1f} % on the EnergyPlus side —\n"
        "a change of side, not of degree.",
        xy=(0.985, 0.565), xycoords="axes fraction", ha="right", va="top",
        fontsize=7.2, color=F.INK, linespacing=1.45,
        bbox=dict(boxstyle="round,pad=0.35", facecolor="white",
                  edgecolor=F.MUTED, linewidth=0.7),
    )
    return {
        "wall_mean": float(wall.mean()),
        "site_mean": float(site.mean()),
        "factor": float(site.mean() / wall.mean()),
        "wall_above_pivot": 100.0 * float((wall > 4).mean()),
        "site_above_pivot": 100.0 * float((site > 4).mean()),
    }


def build() -> dict:
    prov = F.load_ep_hourly_provenance()
    corrected = F.load_ep_hourly("corrected_matched")
    published_wind = F.load_ep_hourly("as_published_wind")
    baseline_ref = F.load_ep_hourly("baseline_repaired")

    published = F.load_ep()           # the superseded reference, for what the defects cost
    repaired = F.load_validation_corrected()
    ep_published_H = published["Heating"]["ep"]
    ep_repaired_H = repaired["baseline"]["Heating"]["ep"]
    cost_kWh = ep_repaired_H - ep_published_H
    cost_pct = 100.0 * cost_kWh / ep_published_H

    station = F.load_wind("station")["summary"]
    terrain = F.load_wind("terrain")["summary"]

    fig, axes = plt.subplots(2, 2, figsize=(13.6, 11.0))
    fig.subplots_adjust(left=0.062, right=0.982, top=0.818, bottom=0.212,
                        hspace=0.52, wspace=0.19)

    p1 = _panel_1(axes[0][0], corrected)
    p2 = _panel_2(axes[0][1], corrected)
    p3 = _panel_3(axes[1][0], baseline_ref)
    p4 = _panel_4(axes[1][1], published_wind)

    titles = [
        ("1  Zero designed ventilation", "repaired state instrumented",
         f"Consequence: repairing defects 1–3 moves the reference's heating from "
         f"{ep_published_H:,.2f} to {ep_repaired_H:,.2f} kWh, {cost_kWh:+,.2f} kWh "
         f"({cost_pct:+.1f} %). The three are not separated anywhere in the committed "
         f"results, so no share of that is attributed to any one of them."),
        ("2  Intermittent outdoor air", "repaired state instrumented",
         f"Consequence: part of the same {cost_kWh:+,.2f} kWh. Outdoor air attached to an "
         f"ideal-loads system is delivered only while that system runs, and not at all "
         f"while the zone free-floats in the deadband."),
        ("3  Humidification booked as heating", "repaired state instrumented",
         f"Consequence: ≈{HUMIDIFICATION_KWH:.0f} kWh/yr of the same total. Masked by "
         f"defect 1 — with no air flowing there was nothing to humidify — so it appeared "
         f"only once defects 1 and 2 were fixed."),
        ("4  Wind at the wrong height", "DEFECTIVE state instrumented",
         f"Consequence: on the canonical state, heating "
         f"{terrain['H_dyn'] - station['H_dyn']:+.2f} kWh and cooling "
         f"{terrain['C_dyn'] - station['C_dyn']:+.2f} kWh. The C2 correction's effect on "
         f"cooling reverses sign, {station['delta_C']:+.2f} → {terrain['delta_C']:+.2f} kWh. "
         f"Resolving this also revealed the terrain-correction mismatch of Section 4.4."),
    ]
    import textwrap

    for ax, (title, state, consequence) in zip(axes.ravel(), titles):
        colour = DEFECT_COLOR if state.startswith("DEFECTIVE") else F.MUTED
        ax.set_title(title, pad=18, loc="left")
        ax.text(0.0, 1.018, state, transform=ax.transAxes, ha="left", va="bottom",
                fontsize=7.0, color=colour, fontweight="bold")
        # Below the axes rather than above it: three wrapped lines of consequence
        # will not fit between a panel title and the plot.
        ax.text(0.0, -0.185, textwrap.fill(consequence, 96),
                transform=ax.transAxes, ha="left", va="top",
                fontsize=7.0, color="#4D4D4D", linespacing=1.45)

    fig.text(
        0.5, 0.988,
        "F11 — How the four defects in the EnergyPlus reference model were found\n"
        "Each has a visible signature in an hourly series; none of the four is visible "
        "in an annual total",
        ha="center", va="top", fontsize=12, fontweight="bold", linespacing=1.45,
    )
    fig.text(
        0.5, 0.912,
        "Hourly EnergyPlus 24.1.0 output, regenerated from the committed IDFs with output "
        "variables added and nothing else changed; every run reproduces the committed annual "
        "totals before its series are drawn.\n"
        "Only defect 4 has a committed defective input, so panel 4 is instrumented in the "
        "defective state and panels 1–3 in the repaired state, with the defective reading "
        "marked as an explicit gap.",
        ha="center", va="top", fontsize=7.8, color="#4D4D4D", linespacing=1.45,
    )

    fig.text(
        0.5, 0.100,
        "$\\bf{All\\ four\\ produced\\ plausible\\ annual\\ totals\\ and\\ raised\\ no\\ warning.}$  "
        "The reference ran to completion, its severe-error count was zero, and its annual "
        f"heating of {ep_published_H:,.1f} kWh is an unremarkable number for this dwelling — "
        "it was wrong by\n"
        f"{cost_kWh:,.0f} kWh, and the only way to see that was to look at the hourly streams. "
        "A validation that compares annual totals cannot detect any of these four, which is "
        "the point the paper makes about detailed reference models.",
        ha="center", va="top", fontsize=8.0, color=F.INK, linespacing=1.5,
        bbox=dict(boxstyle="round,pad=0.6", facecolor="#FFF7E6",
                  edgecolor="#E69F00", linewidth=0.9),
    )

    files = F.save(fig, "F11_reference_model_defects")

    return {
        "id": "F11",
        "title": "How the four reference-model defects were found",
        "files": files,
        "sources": [
            "results/paper/validation_corrected/hourly/hourly_corrected_matched.csv (panels 1, 2)",
            "results/paper/validation_corrected/hourly/hourly_baseline_repaired.csv (panel 3)",
            "results/paper/validation_corrected/hourly/hourly_as_published_wind.csv (panel 4)",
            "results/paper/validation_corrected/hourly/provenance.json",
            "results/paper/validation_corrected/alignment.md (the four defects, and the 686 h and ~300 kWh figures)",
            "results/paper/baseline_vs_ep_v2/baseline_vs_energyplus.csv (the superseded reference, for what the defects cost)",
            "results/paper/wind_profile/wind_stats_station.json, wind_stats_terrain.json (panel 4 consequence)",
        ],
        "numbers": [
            f"Defect 1 — ideal-loads outdoor-air mass flow: 0.0000 kg/s in all 8,760 h "
            f"({p1['oa_nonzero_hours']} non-zero hours). Repaired zone air exchange delivers a mean "
            f"{p1['vent_mean']:.4f} kg/s in all 8,760 h, i.e. H_ve = {p1['H_ve_measured']:.1f} W/K "
            f"against the ISO side's {H_VE_ISO} W/K",
            f"Defect 2 — the ideal-loads system runs {p2['on_hours']:,} of 8,760 h "
            f"({p2['on_pct']:.1f} %) in the repaired matched case; {HOURS_AS_PUBLISHED} h "
            f"({100 * HOURS_AS_PUBLISHED / 8760:.1f} %) as published. ISO 52016-1 applies H_ve in all 8,760",
            f"Defect 3 — reference cumulative heating {p3['end_kWh']:,.2f} kWh; total minus sensible "
            f"= {p3['gap_kWh']:.3f} kWh in every hour. The defective control booked "
            f"≈{HUMIDIFICATION_KWH:.0f} kWh/yr as heating (committed estimate, endpoint only)",
            f"Defect 4 — west-wall surface wind {p4['wall_mean']:.3f} m/s at z = 1.35 m against the "
            f"ISO side's {p4['site_mean']:.3f} m/s, a factor of {p4['factor']:.2f}; "
            f"{p4['site_above_pivot']:.1f} % of hours above the 4 m/s pivot on the ISO side against "
            f"{p4['wall_above_pivot']:.1f} % on the EnergyPlus side",
            f"What the first three cost: EnergyPlus heating {ep_published_H:,.2f} kWh as published "
            f"against {ep_repaired_H:,.2f} kWh repaired, {cost_kWh:+,.2f} kWh ({cost_pct:+.1f} %)",
            f"What the fourth cost: canonical heating "
            f"{terrain['H_dyn'] - station['H_dyn']:+.2f} kWh, cooling "
            f"{terrain['C_dyn'] - station['C_dyn']:+.2f} kWh; the C2 effect on cooling reverses sign, "
            f"{station['delta_C']:+.2f} → {terrain['delta_C']:+.2f} kWh",
            f"EnergyPlus version used for the re-run: {prov['energyplus']}",
        ],
        "note": (
            f"**This figure required a re-run, and is the only one in the set that did.** The raw "
            "EnergyPlus output directory is gitignored as regenerable intermediate "
            "(`.gitignore`: `results/paper/baseline_vs_ep_v2/energyplus/`), so none of the four "
            "hourly series existed in the repository. `tools/diagnostics/"
            "ep_hourly_defect_signatures.py` regenerates them from the **committed** IDFs with "
            "`Output:Variable` lines added and no input to any model changed, and asserts each "
            "run against the committed annual totals before writing: heating 148.973 / cooling "
            "21.590 kWh on the matched case, 2081.972 / 697.348 kWh on the baseline reference, "
            "and surface-wind means of 2.233 and 3.182 m/s. All five assertions passed on "
            "EnergyPlus 24.1.0, the version the paper used. The series are committed under "
            "`results/paper/validation_corrected/hourly/`.\n\n"
            "**Panels 1–3 are in the repaired state.** Only defect 4 has a committed defective "
            "input — the pre-height-fix IDF retained under `results/paper_pre_wind_profile/` — so "
            "it is the only one instrumented in the state that carried the defect. No defective "
            "model was re-created in order to draw the other three, and no series is "
            "reconstructed from an annual total.\n\n"
            "**Two quantities are quoted rather than measured, and are marked on the figure.** "
            "The 686 ideal-loads run hours of the defective configuration (`alignment.md`) — the "
            "repaired case instrumented here runs 824 h, because delivering the ventilation air "
            "every hour raises the load the plant meets. And the ≈300 kWh/yr the "
            "`ConstantSupplyHumidityRatio` control booked as heating (`alignment.md`, "
            "`examples/baseline_vs_energyplus.py`), which is drawn as an explicit hatched gap at "
            "the year end, not as a curve — its endpoint is committed, its path through the year "
            f"is not. The individual shares of defects 1, 2 and 3 in the {cost_kWh:+,.2f} kWh they "
            "cost together are not separated anywhere in the committed results, and are not "
            "apportioned here."
        ),
        "placement": "supplementary",
    }


if __name__ == "__main__":
    F.apply_style()
    print(build())
